SOLVER:
  # optimizer
  OPTIMIZER_TYPE: AdamW
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  AMSGRAD: False
  # lr_scheduler
  LR_SCHEDULER_NAME: WarmupPolyLR
  MAX_ITER: 90000
  POLY_LR_POWER: 0.9
  POLY_LR_CONSTANT_ENDING: 0.0
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear

  BETAS: [0.95, 0.99]
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0001

  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
